[workspace]
authors = ["Christian Jorgensen <cajorgensen@wisc.edu>"]
channels = ["conda-forge"]
name = "example"
platforms = ["win-64", 'osx-arm64', 'win-64', "linux-64"]
version = "0.1.0"

[tasks.start]
description = 'Run Lab'
depends-on = ['lab']

[tasks.lab]
description = 'Launch Jupyter Lab'
cmd = 'jupyter lab'

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
